#!/usr/bin/bash
# -*- explicit-shell-file-name: /bin/bash; -*-

BASE_DIR=$(dirname "${BASH_SOURCE[0]}")
source "${BASE_DIR:-.}/zfs.sh"

[ $UID -eq 0 ] || {
    echo "must be run as super user"
    exit 1
}

ZFS_SEND_ARGS="-v" ZFS_RECV_ARGS="-vF" zfs-backup -i nvme-ssd-2tb/vm-images hdd-mirror0/vm-images
